name: pull request lint

on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  commitLint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: linting
        uses: wagoid/commitlint-github-action@v2